### ISSUE TITLE
Agent参数问题

### ISSUE THREAD

**Issue by hoganzhao** [Maplemx/Agently#101]
Exception in thread Thread-4 (start_in_theard):
Traceback (most recent call last):
  File "/home/hogan/.local/lib/python3.11/site-packages/Agently/Agent/Agent.py", line 240, in start_in_theard
    reply = loop.run_until_complete(self.start_async(request_type))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/hogan/.local/lib/python3.11/site-packages/Agently/Agent/Agent.py", line 227, in start_async
    raise(e)
  File "/home/hogan/.local/lib/python3.11/site-packages/Agently/Agent/Agent.py", line 177, in start_async
    event_generator = await self.request.get_event_generator(request_type)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hogan/.local/lib/python3.11/site-packages/Agently/Request/Request.py", line 116, in get_event_generator
    response_generator = await request_plugin_export["request_model"](request_data)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hogan/.local/lib/python3.11/site-packages/Agently/plugins/request/OAIClient.py", line 208, in request_model
    stream = await client.chat.completions.create(**request_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hogan/.local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1181, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/home/hogan/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1790, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hogan/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1493, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hogan/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1546, in _request
    return await self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hogan/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1615, in _retry_request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hogan/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1584, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': 'Range of input length should be [1, 6000]', 'type': 'invalid_request_error'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hogan/.local/lib/python3.11/site-packages/Agently/Agent/Agent.py", line 243, in start_in_theard
    raise Exception(f"[Agent Request] Error: { str(e) }")
Exception: [Agent Request] Error: Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': 'Range of input length should be [1, 6000]', 'type': 'invalid_request_error'}}

**Comment by Maplemx** [comment]
这个是一个模型请求的报错，模型给你的信息是，输入的信息长度应该在1-6000之间，需要检查一下你的输入是否超长了

这通常跟你使用的模型的上下文窗口限制，以及你是否根据模型要求修改了窗口长度相关的参数，比如maxLength
