### ISSUE TITLE
运行quick_start_demo.py时卡死

### ISSUE THREAD

**Issue by Cinalin** [Maplemx/Agently#17]
在跑quick_start_demo.py的任意一个示例，都出现了卡死的问题，以最简单的quick_start()为例，一直没反应，按Ctrl+C后显示如下内容，不知道怎么解决
```
Traceback (most recent call last):
  File "/home/lin/Documents/science_agent/Agently/demo/python/quick_start_demo.py", line 29, in <module>
    quick_start()
  File "/home/lin/Documents/science_agent/Agently/demo/python/quick_start_demo.py", line 24, in quick_start
    .start()
  File "/home/lin/anaconda3/envs/py310/lib/python3.10/site-packages/Agently/Session.py", line 141, in start
    with concurrent.futures.ThreadPoolExecutor() as executor:
  File "/home/lin/anaconda3/envs/py310/lib/python3.10/concurrent/futures/_base.py", line 649, in __exit__
    self.shutdown(wait=True)
  File "/home/lin/anaconda3/envs/py310/lib/python3.10/concurrent/futures/thread.py", line 235, in shutdown
    t.join()
  File "/home/lin/anaconda3/envs/py310/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/lin/anaconda3/envs/py310/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
```

**Comment by Maplemx** [comment]
ctrl+c的时候因为强制中断了线程，报threading错误是正常现象，所以需要看一下为什么没有反应

**Comment by Maplemx** [comment]
例如，是不是没有挂代理，导致网络请求不通
如果切换MiniMax这样的国内模型服务，是否还会出现问题

**Comment by Cinalin** [comment]
非常感谢您的回复！debug发现确实是代理的问题，原本直接运行以下代码由于网络请求不通导致timeout，
`def quick_start():
    result = worker\
        .input("Give me 5 words and 1 sentence.")\
        .output({
            "words": ("Array",),
            "sentence": ("String",),
        })\
        .start()
    print(result)
    print(result["words"][2])
    return

quick_start()`
后面加了
`proxy = "socks5://127.0.0.1:7890"
worker.set_proxy(proxy)`就可以了。

**Comment by Cinalin** [comment]
非常感谢您的回复！debug发现确实是代理的问题，原本直接运行以下代码由于网络请求不通导致timeout，
加了
```
proxy = "socks5://127.0.0.1:7890"
worker.set_proxy(proxy)
```
就可以了。
