### ISSUE TITLE
KeyError: 'choices'

### ISSUE THREAD

**Issue by peterz3g** [Maplemx/Agently#22]
按readme第一个简单demo运行，报错了。代码只修改了如下一行
==========================================
worker.set_llm_name("GPT").set_llm_auth("GPT",api_token).set_llm_url("GPT", api_base)  
因为网络不通，因此llm_url换成了代理url
===========================================

Traceback (most recent call last):
  File "/home/chatai/git_pro/ly_src/script/test_agent.py", line 19, in <module>
    .start()
  File "/root/miniconda3/envs/chatai/lib/python3.10/site-packages/Agently/Session.py", line 143, in start
    result = future.result()
  File "/root/miniconda3/envs/chatai/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/root/miniconda3/envs/chatai/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/root/miniconda3/envs/chatai/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/miniconda3/envs/chatai/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/chatai/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/miniconda3/envs/chatai/lib/python3.10/site-packages/Agently/Session.py", line 113, in __start
    await work_node["main"](\
  File "/root/miniconda3/envs/chatai/lib/python3.10/site-packages/Agently/work_nodes/request.py", line 38, in request
    await process["request_main"][request_method](runtime_ctx, **kwargs)
  File "/root/miniconda3/envs/chatai/lib/python3.10/site-packages/Agently/work_nodes/request.py", line 28, in request_main_default
    response = await process["request_llm"][llm_name](request_data, listener)
  File "/root/miniconda3/envs/chatai/lib/python3.10/site-packages/Agently/work_nodes/llm_request/GPT.py", line 54, in request
    await listener.emit("response:done", response)
  File "/root/miniconda3/envs/chatai/lib/python3.10/site-packages/Agently/Session.py", line 22, in emit
    await handler(*args, **kwargs)
  File "/root/miniconda3/envs/chatai/lib/python3.10/site-packages/Agently/work_nodes/llm_request/GPT.py", line 100, in handle_response_done
    await listener.emit("extract:done_full", done_data["choices"][0])
KeyError: 'choices'

**Comment by Maplemx** [comment]
有一个可能是代理的API返回的数据结构和官方返回的数据结构并不相同，可能需要重写数据解析部分，建议查看(/work_nodes/llm_request/GPT.py)[https://github.com/Maplemx/Agently/blob/main/src/python/v2/work_nodes/llm_request/GPT.py] 里的handle_response方法，重新做一下数据映射

在新版本我想想怎么把映射的配置做成接口

**Comment by Maplemx** [comment]
还有一种可能，是接口报错了，可以在GPT.py那个文件100行附近把response的完整结果打印一下，看看报什么错误
